[package]
name = "rpisd"
version = "0.1.0"
edition = "2021"
description = "Driver for Rpi sd card"
publish = false

[dependencies]
novuskinc = "0.1.1"
rpi = { path = "../../../rpi/" }
storage = { path = "../../" }
