[package]
name = "nkuefi"
version = "0.1.0"
edition = "2021"
description = "Novusk Kernel UEFI driver"
license = "MIT"
publish = false

[target.'cfg(target_arch = "x86_64")'.dependencies]
uart_16550 = "0.2.15"
