[package]
name = "storage"
version = "0.1.0"
edition = "2021"
description = "Initializes disk/card and Fs"
license = "MIT"
publish = false

[dependencies]
novuskinc = "0.1.1"
printk = { path = "../../kernel/printk/" }

[features]
empty = []
