[package]
name = "rpi2kernel"
version = "0.1.0"
edition = "2021"
description = "RPi 2 specific kernel"
publish = false

[dependencies]
armfb = { path = "../../gpu/armfb/" }
console = { path = "../../../kernel/console/" }
fb = { path = "../../fb/" }
kinfo = { path = "../../../kernel/kinfo/" }
konfig = { path = "../../../kernel/konfig/" }
printk = { path = "../../../kernel/printk/" }
rpi = { path = "../", features = ["rpi2"] }
