[package]
name = "lba"
version = "0.1.0"
edition = "2021"
description = "Logical Block Addressing (LBA) driver"
publish = false

[dependencies]
novuskinc = "0.1.1"
printk = { path = "../../../kernel/printk/" }
storage = { path = "../" }
x86_64 = "0.14.7"
